spring:
  datasource:
    url: jdbc:mysql://localhost:3306/git_toolchain_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.office365.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  security:
    require-ssl: false

  data:
    mongodb:
      uri: mongodb+srv://team3squad1:team31234@cluster0.glludhu.mongodb.net/GitToolchainNotification?retryWrites=true&w=majority



innerSourceApi:
  baseUrl: 'https://innersource.soprasteria.com/api/v4'



# Optional mail properties (uncomment if needed)
#        smtp:
#          timeout: 5000
#          writetimeout: 5000
#          connectiontimeout: 5000






